### ISSUE TITLE
move some GNI provider code into common  - tracking issue 

### ISSUE THREAD

**Issue by hppritcha** [ofiwg/libfabric#1447]
Some of the code in the GNI provider should be moved to common code area.  This issue tracks the individual components that have been selected for moving go common code:
- [x] rbtree code (#1448)
- [x] fasthash code (#1449)
- [ ] gnix bitmap code (#1450)
- [ ] gnix freelist code (#1450)
- [ ] extensions to dlist iterator methods and rwlock defs (gnix_util.h)
- [ ] some of the defines in gnix.h (IN, OUT, INOUT, compiler_barrier, unlikely, etc.)
- [ ] hash table code

There may be other functionality which could eventually be moved in to common code.

**Comment by bturrubiates** [comment]
@hppritcha @shefty @jsquyres 

I think it'd also be useful to move over the `unlikely` and `likely` [definitions](https://github.com/ofiwg/libfabric/blob/master/prov%2Fgni%2Finclude%2Fgnix.h#L80-L85).

**Comment by shefty** [comment]
Common code has a variety of abstractions now.  No need for gni provider churn 5 years later...
