### ISSUE TITLE
v1.3.0 release checklist

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#1905]
## Make a perfect tarball

* For libfabric:
  * [x] Update the version numbers in `include/rdma/fabric.h`:
  * [x] Update the shared library version number(s) in `Makefile.am` [per the GNU Libtool shared library version number rules](https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html)
  * Update all documentation files (especially including dates and version numbers), including:
    * [x] `README.md`
    * [x] `AUTHORS`
    * [x] Update the years in the copyright notices in `COPYING`
    * [Provider Feature Matrix for v1.3.0](https://github.com/ofiwg/libfabric/wiki/Provider-Feature-Matrixv1.3.0)
      * [x] GNI provider
      * [x] MXM
      * [x] PSM provider
      * [x] PSM2 provider
      * [x] Sockets provider
      * [x] UDP provider
      * [x] usnic provider
      * [x] verbs provider
    * `NEWS.md`
      * [x] GNI provider
      * [x] MXM
      * [x] PSM provider
      * [x] PSM2 provider
      * [x] Sockets provider
      * [x] UDP provider
      * [x] usnic provider
      * [x] verbs provider
    * Man pages
      * [x] `man/fi_gni.7.md`
      * [x] `man/fi_mxm.7.md`
      * [x] `man/fi_psm.7.md`
      * [x] `man/fi_psm2.7.md`
      * [x] `man/fi_sockets.7.md`
      * [x] `man/fi_udp.7.md`
      * [x] `man/fi_usnic.7.md`
      * [x] `man/fi_verbs.7.md`
    * [x] ...any other doc files that may not be included in this list
* For fabtests:
  * [x] Update the version number in `configure.ac` to the final release version
  * Update all documentation files (especially including dates and version numbers):
    * [x] `README`
    * [x] `README.md`
    * [x] `AUTHORS`
    * [x] Update the years in the copyright notices in `COPYING`
    * [x] ...any other doc files that may not be included in this list
* [x] Update the libfabric version number in `configure.ac` to the final release version
* [x] Update the libfabric release date in `NEWS.md`
* [x] Update the fabtests version number in `configure.ac` to the final release version
* [x] Make final `libfabric-x.y.z.tar.gz` and `libfabric-x.y.z.bz2` tarballs
* [x] Make final `fabtests-x.y.z.tar.gz` and `fabtests-x.y.z.bz2` tarballs

## Ensure that the tarball actually works

* [x] Ensure libfabric `make distcheck` passes
* Build and install libfabric (from a tarball)
  * [x] Check that the version number and release date is correct in the installed man pages
* [x] Build and install fabtests (from a tarball)
* [x] Ensure fabtests `make distcheck` passes
* Ensure all providers pass all (relevant) tests
  * [x] gni
  * [x] mxm
  * [x] psm
  * [x] psm2
  * [x] sockets
  * [x] udp
  * [x] usnic
  * [x] verbs
* Build and install previous version of libfabric (from a tarball)
* Build and install previous version of fabtests against previous version of libfabric (from a tarball)
* `rm -rf` the installation of the previous version of libfabric
* Set `LD_LIBRARY_PATH` to point to the installation of the new libfabric
* Re-run all fabtests and ensure that they still pass
  * [x] gni
  * [x] mxm
  * [x] psm
  * [x] psm2
  * [x] sockets
  * [x] udp
  * [x] usnic
  * [x] verbs

## Test packaging

* [x] Ensure that building a libfabric source RPM works on a RHEL system
* [x] Ensure that building the libfabric binary RPMs (`libfabric` and `libfabric-devel`) work on a RHEL system
* [x] Install both RPMs on an RHEL system
* [x] Test building and running fabtests against the RPM-installed libfabric
* [x] Test building a libfabric-based program with the output from `pkg-config` with the RPM-installed `libfabric.pc`
* [x] Uninstall `libfabric-devel` and ensure libfabric programs still run correctly

## Do the release

* [x] `git tag -a vX.Y.Z` on the libfabric master branch
* [x] `git tag -a vX.Y.Z` on the fabtests master branch
* [x] `git push --tags --dry-run` to libfabric.  Remove `--dry-run` when you're convinced it is correct.
* [x] `git push --tags --dry-run` to fabtests.  Remove `--dry-run` when you're convinced it is correct.
* [x] Make a libfabric release corresponding to the git tag on https://github.com/ofiwg/libfabric/releases
* [x] Make a fabtests release corresponding to the git tag on https://github.com/ofiwg/fabtests/releases
* Copy the `man/*.[0-9].md` files from *exactly* the same Git hash that was used to make the official tarball to the `gh-pages` branch of the libfabric Git repo
  * [x] Put them in `vX.Y.Z/man/`
  * [x] Also put an `index.md` file in that directory (copy one from the prior releases and edit it to reflect this version, and add/remove any man pages as relevant for this release)
* Update the main `index.md` page:
  * [x] Add links to the new libfabric and fabtests release tarballs
  * [x] Add link for the man pages for this release
* [x] Close #1895 
* [x] Close the relevant Github milestone in `ofiwg/libfabric` and `ofiwg/fabtests`
* [x] Re-target all still-open v1.3.0 issues for v1.3.1 or v1.4.0, as appropriate
* [x] Ensure that new Github milestones exist in `ofiwg/libfabric` and `ofiwg/fabtests` for the next release
* [x] Update the libfabric version number in `configure.ac` to `<NEXT_VERSION>a1`
* [x] Update the fabtests version number in `configure.ac` to `<NEXT_VERSION>a1`
* [x] Send an email to the `ofiwg` mailing list announcing the release

**Comment by jsquyres** [comment]
Note that closing this issue will also mark fixing #1895.

**Comment by jsquyres** [comment]
@shefty What is the status of releasing v1.3.0?  Cisco needs this release RSN (our QA is now over a week behind schedule because we were expecting the v1.3.0 release on 1 April).  Thanks.

**Comment by shefty** [comment]
I was hoping to get a release out before the OFA workshop as well, but that requires creating the first rc at least 2 weeks before the targeted release date.  I think we're ready for the 1.3 release now, but let me check with the MPI folks working on the verbs provider.  It looks like they have one patch to merge - done just now.

There's a separate patch to fabtests, but I'm hesitant to merge that one immediately before a release based on the risk of the change.

**Comment by shefty** [comment]
@jsquyres - are you creating the 1.3. package?

**Comment by jsquyres** [comment]
Yes, I'm happy to create the tarball and complete this ticket.

**Comment by jsquyres** [comment]
v1.3.0 has been released.
