### ISSUE TITLE
v1.4.1 release checklist

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#2688]
## Make a perfect tarball
- For libfabric:
  - [x] Make a v1.4.x branch
  - [x] Cherry-pick relevant commits from master
  - [x] Update the version numbers in `include/rdma/fabric.h`:
  - [x] Update the shared library version number(s) in `Makefile.am` [per the GNU Libtool shared library version number rules](https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html)
  - Update all documentation files (especially including dates and version numbers), including:
    - [x] `README.md`
    - [x] `AUTHORS` (via `git log --pretty=format:'%aN <%aE>' | sort --ignore-case | uniq > AUTHORS`)
    - [x] Update the years in the copyright notices in `COPYING`
    - [Provider Feature Matrix for v1.4.1](https://github.com/ofiwg/libfabric/wiki/Provider-Feature-Matrix-v1.4.1)
      - [x] GNI provider
      - [x] MXM
      - [x] PSM provider
      - [x] PSM2 provider
      - [x] Sockets provider
      - [x] UDP provider
      - [x] usnic provider
      - [x] verbs provider
    - `NEWS.md`
      - [x] GNI provider
      - [x] MXM
      - [x] PSM provider
      - [x] PSM2 provider
      - [x] Sockets provider
      - [x] UDP provider
      - [x] usnic provider
      - [x] verbs provider
    - Man pages
      - [x] `man/fi_gni.7.md`
      - [x] `man/fi_mxm.7.md`
      - [x] `man/fi_psm.7.md`
      - [x] `man/fi_psm2.7.md`
      - [x] `man/fi_sockets.7.md`
      - [x] `man/fi_udp.7.md`
      - [x] `man/fi_usnic.7.md`
      - [x] `man/fi_verbs.7.md`
    - [x] ...any other doc files that may not be included in this list
- For fabtests:
  - [x] Update the version number in `configure.ac` to the final release version
  - Update all documentation files (especially including dates and version numbers):
    - [x] `README`
    - [x] `README.md`
    - [x] `AUTHORS` (via `git log --pretty=format:'%aN <%aE>' | sort --ignore-case | uniq > AUTHORS`)
    - [x] Update the years in the copyright notices in `COPYING`
    - [x] ...any other doc files that may not be included in this list
- [x] Update the libfabric version number in `configure.ac` to the final release version
- [x] Update the libfabric release date in `NEWS.md`
- [x] Update the fabtests version number in `configure.ac` to the final release version
- [x] Make final `libfabric-x.y.z.tar.gz` and `libfabric-x.y.z.bz2` tarballs
- [x] Make final `fabtests-x.y.z.tar.gz` and `fabtests-x.y.z.bz2` tarballs
## Ensure that the tarball actually works
- [x] Ensure libfabric `make distcheck` passes
- Build and install libfabric (from a tarball)
  - [x] Check that the version number and release date is correct in the installed man pages
- [x] Build and install fabtests (from a tarball)
- [x] Ensure fabtests `make distcheck` passes
- Ensure all providers pass all (relevant) tests
  - [ ] gni
  - [ ] mxm
  - [ ] psm
  - [ ] psm2
  - [x] sockets
  - [ ] udp
  - [x] usnic
  - [x] verbs
- Build and install previous version of libfabric (from a tarball)
- Build and install previous version of fabtests against previous version of libfabric (from a tarball)
- `rm -rf` the installation of the previous version of libfabric
- Set `LD_LIBRARY_PATH` to point to the installation of the new libfabric
- Re-run all fabtests and ensure that they still pass
  - [ ] gni
  - [ ] mxm
  - [ ] psm
  - [ ] psm2
  - [x] sockets
  - [ ] udp
  - [x] usnic
  - [x] verbs
## Test packaging
- [x] Ensure that building a libfabric source RPM works on a RHEL system
- [x] Ensure that building the libfabric binary RPMs (`libfabric` and `libfabric-devel`) work on a RHEL system
- [x] Install both RPMs on an RHEL system
- [x] Test building and running fabtests against the RPM-installed libfabric
- [x] Test building a libfabric-based program with the output from `pkg-config` with the RPM-installed `libfabric.pc`
- [x] Uninstall `libfabric-devel` and ensure libfabric programs still run correctly
## Do the release
- [x] `git tag -a vX.Y.Z` on the libfabric master branch
- [x] `git tag -a vX.Y.Z` on the fabtests master branch
- [x] `git push --tags --dry-run` to libfabric.  Remove `--dry-run` when you're convinced it is correct.
- [x] `git push --tags --dry-run` to fabtests.  Remove `--dry-run` when you're convinced it is correct.
- [x] Make a libfabric release corresponding to the git tag on https://github.com/ofiwg/libfabric/releases
- [x] Make a fabtests release corresponding to the git tag on https://github.com/ofiwg/fabtests/releases
- Copy the `man/*.[0-9].md` files from _exactly_ the same Git hash that was used to make the official tarball to the `gh-pages` branch of the libfabric Git repo
  - [x] Put them in `vX.Y.Z/man/`
  - [x] Also put an `index.md` file in that directory (copy one from the prior releases and edit it to reflect this version, and add/remove any man pages as relevant for this release)
- Update the main `index.md` page:
  - [x] Add links to the new libfabric and fabtests release tarballs
  - [x] Add link for the man pages for this release
- [x] Close the relevant Github milestone in `ofiwg/libfabric` and `ofiwg/fabtests`
- [x] Re-target all still-open v1.4.1 issues for v1.5.1 or v1.5.0, as appropriate
- [x] Ensure that new Github milestones exist in `ofiwg/libfabric` and `ofiwg/fabtests` for the next release
- [x] Update the libfabric version number in `configure.ac` to `<NEXT_VERSION>a1`
- [x] Update the fabtests version number in `configure.ac` to `<NEXT_VERSION>a1`
- [x] Send an email to the `ofiwg` mailing list announcing the release

**Comment by shefty** [comment]
Yes - I was thinking ASAP.  I'll see if there are any other fixes to bring it, but I'd like any to be really, really simple and small.

**Comment by jsquyres** [comment]
Ok.  Waiting for Travis at this point to merge some PRs to master before cherry-picking them to the v1.4.x branch.  Also still discussing with Jason G on #2684 what the Right solution should be.

**Comment by shefty** [comment]
There are are few fixes to pull into 1.4.1.  I'll try to get those merged in today.

**Comment by shefty** [comment]
I pushed 5 fixes to the psm/psm2 providers into the v1.4.x branch that were cherry-picked from master.  My remote was set to 'ofiwg' rather than 'shefty' so the push went directly into the ofiwg repo, rather than my personal repo, where I intended.  So no PR for the fixes ended up being created.

**Comment by jsquyres** [comment]
@shefty We're making a fabtests v1.4.1, too, right?

**Comment by shefty** [comment]
I can go either way on fabtests.  There have been some fixes, and I don't see anything related to the ABI update.  So it may be okay to form 1.4.1 from the head.

**Comment by shefty** [comment]
@a-ilango is out until next Monday.  I've scanned the verbs provider for fixes, but I think we want to wait for input from Arun and the other verbs developers.

The sockets provider is more difficult, since we've lost any maintainer.  I've made a list of socket provider fixes, but I'm still trying to decide if any are important enough for this release.

**Comment by a-ilango** [comment]
Verbs provider doesn't have any critical fixes that needs go into 1.4.1

**Comment by shefty** [comment]
I think we're good to do.  The changes to the socket provider fix problems that have been there since forever.

**Comment by shefty** [comment]
@jsquyres - Are we just needing to create the tarballs and validate them at this point?  I'd like to verify this with the OFED release as part of the testing, but they will need a package.  Did you want to go with an rc for this, or just jump to the release?

**Comment by jsquyres** [comment]
Yes, all we need to do is the verification.

Let me make a pair of tarballs: an rc and a final.  I'll publish the rc's so that you can test them.  Then, if we're good, the final tarballs will be available as well (that were made at the same time, from the same hash, ...etc.).

**Comment by shefty** [comment]
Sounds good - thanks

**Comment by jsquyres** [comment]
rc tarballs posted here: http://openfabrics.org/downloads/ofi/

**Comment by jsquyres** [comment]
@shefty Did the OFED people confirm that this fixed their issue?  Should we release v1.4.1/final?

**Comment by shefty** [comment]
I have not seen where they confirmed things work.  But they released an OFED package with 1.4.1 and I haven't seen any complaints either.  I requested that they update the bugzilla report with the test results.  I'm 99% convinced that everything is fine.

**Comment by shefty** [comment]
OFED confirmed that 1.4.1 works for them.  BUT.... Intel MPI is reporting a crash in verbs.  I'm trying to find out if that crash is an issue with libfabric or a problem with libibverbs itself.  I think the latter.

**Comment by shefty** [comment]
The other problem does not appear to be related to libfabric.  We can go ahead and publish the previously made releases.  Thanks!

**Comment by jsquyres** [comment]
Cool; I can probably do this tomorrow.

**Comment by jsquyres** [comment]
v1.4.1 has been released.  Closing the issue.
